<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entities\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'firstname', 'lastname', 'employee_id', 'about', 'company_name', 'email', 'company_email', 'status', 'gender', 'report_to', 'department', 'designation', 'location', 'address', 'per_address', 'allowed_login', 'on_training', 'is_manager', 'marital_status', 'probation_end_date', 'joining_date', 'increment_date', 'exit_date', 'user_exit_status', 'date_of_birth', 'marriage_anniversary_date', 'contact_no', 'emergency_contact_no', 'emergency_contact_person', 'driving_license_number', 'pan_number', 'aadhar_number', 'voter_id_number', 'uan_number', 'pf_number', 'esic_number', 'driving_license_image', 'pan_id_image', 'aadhar_id_image', 'voter_id_image', 'lc', 'marksheet', 'offer_later_file', 'joining_letter_file', 'contract_file', 'resume_file', 'appointment_letter', 'increment_letter', 'promotion_letter', 'relieving_letter', 'exp_letter', 'appreciation_letter', 'document_returns_letter', 'no_due_certificate', 'acknowledgement_letter', 'warning_letter', 'primary_account', 'passport_number', 'passport_issue_date', 'passport_expiry_date', 'passport_image', 'visa_number', 'visa_issue_date', 'visa_expiry_date', 'visa_image', 'slack_username', 'linkdin_username', 'facebook_username', 'profile_image', 'twitter_username', 'certifications_courses', 'other_work_experirnce', 'roles', 'user_work', 'user_qualification', 'user_account', 'user_check_in', 'user_leaves', 'approved_leave', 'created_at', 'updated_at', 'deletedAt', 'password', 'rememberToken'];
        }

        return ['__isInitialized__', 'id', 'firstname', 'lastname', 'employee_id', 'about', 'company_name', 'email', 'company_email', 'status', 'gender', 'report_to', 'department', 'designation', 'location', 'address', 'per_address', 'allowed_login', 'on_training', 'is_manager', 'marital_status', 'probation_end_date', 'joining_date', 'increment_date', 'exit_date', 'user_exit_status', 'date_of_birth', 'marriage_anniversary_date', 'contact_no', 'emergency_contact_no', 'emergency_contact_person', 'driving_license_number', 'pan_number', 'aadhar_number', 'voter_id_number', 'uan_number', 'pf_number', 'esic_number', 'driving_license_image', 'pan_id_image', 'aadhar_id_image', 'voter_id_image', 'lc', 'marksheet', 'offer_later_file', 'joining_letter_file', 'contract_file', 'resume_file', 'appointment_letter', 'increment_letter', 'promotion_letter', 'relieving_letter', 'exp_letter', 'appreciation_letter', 'document_returns_letter', 'no_due_certificate', 'acknowledgement_letter', 'warning_letter', 'primary_account', 'passport_number', 'passport_issue_date', 'passport_expiry_date', 'passport_image', 'visa_number', 'visa_issue_date', 'visa_expiry_date', 'visa_image', 'slack_username', 'linkdin_username', 'facebook_username', 'profile_image', 'twitter_username', 'certifications_courses', 'other_work_experirnce', 'roles', 'user_work', 'user_qualification', 'user_account', 'user_check_in', 'user_leaves', 'approved_leave', 'created_at', 'updated_at', 'deletedAt', 'password', 'rememberToken'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyEmail', []);

        return parent::getCompanyEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyEmail($company_email): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyEmail', [$company_email]);

        parent::setCompanyEmail($company_email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerAddress', []);

        return parent::getPerAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerAddress($per_address): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerAddress', [$per_address]);

        parent::setPerAddress($per_address);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', []);

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname($lastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', [$lastname]);

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbout', []);

        return parent::getAbout();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbout($about)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbout', [$about]);

        return parent::setAbout($about);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyName', []);

        return parent::getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyName($company_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyName', [$company_name]);

        return parent::setCompanyName($company_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', [$gender]);

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getReportTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportTo', []);

        return parent::getReportTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setReportTo($report_to)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReportTo', [$report_to]);

        return parent::setReportTo($report_to);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartment', []);

        return parent::getDepartment();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartment($department)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartment', [$department]);

        return parent::setDepartment($department);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesignation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesignation', []);

        return parent::getDesignation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesignation($designation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesignation', [$designation]);

        return parent::setDesignation($designation);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation($location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getOnTraining()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOnTraining', []);

        return parent::getOnTraining();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnTraining($on_training): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnTraining', [$on_training]);

        parent::setOnTraining($on_training);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllowedLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllowedLogin', []);

        return parent::getAllowedLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowedLogin($allowed_login)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowedLogin', [$allowed_login]);

        return parent::setAllowedLogin($allowed_login);
    }

    /**
     * {@inheritDoc}
     */
    public function getisManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getisManager', []);

        return parent::getisManager();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsManager($is_manager)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsManager', [$is_manager]);

        return parent::setIsManager($is_manager);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaritalStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaritalStatus', []);

        return parent::getMaritalStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaritalStatus($marital_status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaritalStatus', [$marital_status]);

        return parent::setMaritalStatus($marital_status);
    }

    /**
     * {@inheritDoc}
     */
    public function getProbationEndDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProbationEndDate', []);

        return parent::getProbationEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setProbationEndDate($probation_end_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProbationEndDate', [$probation_end_date]);

        return parent::setProbationEndDate($probation_end_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getJoiningDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJoiningDate', []);

        return parent::getJoiningDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setJoiningDate($joining_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJoiningDate', [$joining_date]);

        return parent::setJoiningDate($joining_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getIncrementDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncrementDate', []);

        return parent::getIncrementDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIncrementDate($increment_date): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncrementDate', [$increment_date]);

        parent::setIncrementDate($increment_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getExitDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExitDate', []);

        return parent::getExitDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setExitDate($exit_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExitDate', [$exit_date]);

        return parent::setExitDate($exit_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserExitStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserExitStatus', []);

        return parent::getUserExitStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserExitStatus($user_exit_status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserExitStatus', [$user_exit_status]);

        return parent::setUserExitStatus($user_exit_status);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateOfBirth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateOfBirth', []);

        return parent::getDateOfBirth();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateOfBirth($date_of_birth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateOfBirth', [$date_of_birth]);

        return parent::setDateOfBirth($date_of_birth);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarriageAnniversaryDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarriageAnniversaryDate', []);

        return parent::getMarriageAnniversaryDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarriageAnniversaryDate($marriage_anniversary_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarriageAnniversaryDate', [$marriage_anniversary_date]);

        return parent::setMarriageAnniversaryDate($marriage_anniversary_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactNo', []);

        return parent::getContactNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactNo($contact_no)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactNo', [$contact_no]);

        return parent::setContactNo($contact_no);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmergencyContactNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmergencyContactNo', []);

        return parent::getEmergencyContactNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmergencyContactNo($emergency_contact_no)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmergencyContactNo', [$emergency_contact_no]);

        return parent::setEmergencyContactNo($emergency_contact_no);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmergencyContactPerson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmergencyContactPerson', []);

        return parent::getEmergencyContactPerson();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmergencyContactPerson($emergency_contact_person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmergencyContactPerson', [$emergency_contact_person]);

        return parent::setEmergencyContactPerson($emergency_contact_person);
    }

    /**
     * {@inheritDoc}
     */
    public function getDrivingLicenseNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDrivingLicenseNumber', []);

        return parent::getDrivingLicenseNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setDrivingLicenseNumber($driving_license_number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDrivingLicenseNumber', [$driving_license_number]);

        return parent::setDrivingLicenseNumber($driving_license_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getPanNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPanNumber', []);

        return parent::getPanNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPanNumber($pan_number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPanNumber', [$pan_number]);

        return parent::setPanNumber($pan_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getAadharNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAadharNumber', []);

        return parent::getAadharNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setAadharNumber($aadhar_number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAadharNumber', [$aadhar_number]);

        return parent::setAadharNumber($aadhar_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getVoterIdNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVoterIdNumber', []);

        return parent::getVoterIdNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setVoterIdNumber($voter_id_number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVoterIdNumber', [$voter_id_number]);

        return parent::setVoterIdNumber($voter_id_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getUanNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUanNumber', []);

        return parent::getUanNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setUanNumber($uan_number): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUanNumber', [$uan_number]);

        parent::setUanNumber($uan_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getPfNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPfNumber', []);

        return parent::getPfNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPfNumber($pf_number): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPfNumber', [$pf_number]);

        parent::setPfNumber($pf_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsicNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsicNumber', []);

        return parent::getEsicNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsicNumber($esic_number): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsicNumber', [$esic_number]);

        parent::setEsicNumber($esic_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getLc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLc', []);

        return parent::getLc();
    }

    /**
     * {@inheritDoc}
     */
    public function setLc($lc): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLc', [$lc]);

        parent::setLc($lc);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarksheet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarksheet', []);

        return parent::getMarksheet();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarksheet($marksheet): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarksheet', [$marksheet]);

        parent::setMarksheet($marksheet);
    }

    /**
     * {@inheritDoc}
     */
    public function getDrivingLicenseImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDrivingLicenseImage', []);

        return parent::getDrivingLicenseImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDrivingLicenseImage($driving_license_image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDrivingLicenseImage', [$driving_license_image]);

        return parent::setDrivingLicenseImage($driving_license_image);
    }

    /**
     * {@inheritDoc}
     */
    public function getPanIdImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPanIdImage', []);

        return parent::getPanIdImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPanIdImage($pan_id_image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPanIdImage', [$pan_id_image]);

        return parent::setPanIdImage($pan_id_image);
    }

    /**
     * {@inheritDoc}
     */
    public function getAadharIdImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAadharIdImage', []);

        return parent::getAadharIdImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setAadharIdImage($aadhar_id_image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAadharIdImage', [$aadhar_id_image]);

        return parent::setAadharIdImage($aadhar_id_image);
    }

    /**
     * {@inheritDoc}
     */
    public function getVoterIdImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVoterIdImage', []);

        return parent::getVoterIdImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setVoterIdImage($voter_id_image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVoterIdImage', [$voter_id_image]);

        return parent::setVoterIdImage($voter_id_image);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferLaterFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferLaterFile', []);

        return parent::getOfferLaterFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferLaterFile($offer_later_file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferLaterFile', [$offer_later_file]);

        return parent::setOfferLaterFile($offer_later_file);
    }

    /**
     * {@inheritDoc}
     */
    public function getJoiningLetterFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJoiningLetterFile', []);

        return parent::getJoiningLetterFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setJoiningLetterFile($joining_letter_file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJoiningLetterFile', [$joining_letter_file]);

        return parent::setJoiningLetterFile($joining_letter_file);
    }

    /**
     * {@inheritDoc}
     */
    public function getContractFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContractFile', []);

        return parent::getContractFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setContractFile($contract_file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContractFile', [$contract_file]);

        return parent::setContractFile($contract_file);
    }

    /**
     * {@inheritDoc}
     */
    public function getResumeFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResumeFile', []);

        return parent::getResumeFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setResumeFile($resume_file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResumeFile', [$resume_file]);

        return parent::setResumeFile($resume_file);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppointmentLetter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppointmentLetter', []);

        return parent::getAppointmentLetter();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppointmentLetter($appointment_letter): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppointmentLetter', [$appointment_letter]);

        parent::setAppointmentLetter($appointment_letter);
    }

    /**
     * {@inheritDoc}
     */
    public function getIncrementLetter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncrementLetter', []);

        return parent::getIncrementLetter();
    }

    /**
     * {@inheritDoc}
     */
    public function setIncrementLetter($increment_letter): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncrementLetter', [$increment_letter]);

        parent::setIncrementLetter($increment_letter);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotionLetter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotionLetter', []);

        return parent::getPromotionLetter();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromotionLetter($promotion_letter): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromotionLetter', [$promotion_letter]);

        parent::setPromotionLetter($promotion_letter);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelievingLetter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelievingLetter', []);

        return parent::getRelievingLetter();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelievingLetter($relieving_letter): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelievingLetter', [$relieving_letter]);

        parent::setRelievingLetter($relieving_letter);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpLetter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpLetter', []);

        return parent::getExpLetter();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpLetter($exp_letter): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpLetter', [$exp_letter]);

        parent::setExpLetter($exp_letter);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppreciationLetter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppreciationLetter', []);

        return parent::getAppreciationLetter();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppreciationLetter($appreciation_letter): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppreciationLetter', [$appreciation_letter]);

        parent::setAppreciationLetter($appreciation_letter);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentReturnsLetter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentReturnsLetter', []);

        return parent::getDocumentReturnsLetter();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentReturnsLetter($document_returns_letter): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentReturnsLetter', [$document_returns_letter]);

        parent::setDocumentReturnsLetter($document_returns_letter);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoDueCertificate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoDueCertificate', []);

        return parent::getNoDueCertificate();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoDueCertificate($no_due_certificate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoDueCertificate', [$no_due_certificate]);

        parent::setNoDueCertificate($no_due_certificate);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcknowledgementLetter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcknowledgementLetter', []);

        return parent::getAcknowledgementLetter();
    }

    /**
     * {@inheritDoc}
     */
    public function setAcknowledgementLetter($acknowledgement_letter): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcknowledgementLetter', [$acknowledgement_letter]);

        parent::setAcknowledgementLetter($acknowledgement_letter);
    }

    /**
     * {@inheritDoc}
     */
    public function getWarningLetter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWarningLetter', []);

        return parent::getWarningLetter();
    }

    /**
     * {@inheritDoc}
     */
    public function setWarningLetter($warning_letter): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWarningLetter', [$warning_letter]);

        parent::setWarningLetter($warning_letter);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryAccount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimaryAccount', []);

        return parent::getPrimaryAccount();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimaryAccount($primary_account)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimaryAccount', [$primary_account]);

        return parent::setPrimaryAccount($primary_account);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassportNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassportNumber', []);

        return parent::getPassportNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassportNumber($passport_number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassportNumber', [$passport_number]);

        return parent::setPassportNumber($passport_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassportIssueDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassportIssueDate', []);

        return parent::getPassportIssueDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassportIssueDate($passport_issue_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassportIssueDate', [$passport_issue_date]);

        return parent::setPassportIssueDate($passport_issue_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassportExpiryDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassportExpiryDate', []);

        return parent::getPassportExpiryDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassportExpiryDate($passport_expiry_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassportExpiryDate', [$passport_expiry_date]);

        return parent::setPassportExpiryDate($passport_expiry_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassportImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassportImage', []);

        return parent::getPassportImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassportImage($passport_image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassportImage', [$passport_image]);

        return parent::setPassportImage($passport_image);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisaNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisaNumber', []);

        return parent::getVisaNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisaNumber($visa_number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisaNumber', [$visa_number]);

        return parent::setVisaNumber($visa_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisaIssueDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisaIssueDate', []);

        return parent::getVisaIssueDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisaIssueDate($visa_issue_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisaIssueDate', [$visa_issue_date]);

        return parent::setVisaIssueDate($visa_issue_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisaExpiryDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisaExpiryDate', []);

        return parent::getVisaExpiryDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisaExpiryDate($visa_expiry_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisaExpiryDate', [$visa_expiry_date]);

        return parent::setVisaExpiryDate($visa_expiry_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisaImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisaImage', []);

        return parent::getVisaImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisaImage($visa_image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisaImage', [$visa_image]);

        return parent::setVisaImage($visa_image);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlackUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlackUsername', []);

        return parent::getSlackUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlackUsername($slack_username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlackUsername', [$slack_username]);

        return parent::setSlackUsername($slack_username);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkdinUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkdinUsername', []);

        return parent::getLinkdinUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkdinUsername($linkdin_username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkdinUsername', [$linkdin_username]);

        return parent::setLinkdinUsername($linkdin_username);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookUsername', []);

        return parent::getFacebookUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebookUsername($facebook_username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebookUsername', [$facebook_username]);

        return parent::setFacebookUsername($facebook_username);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileImage', []);

        return parent::getProfileImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileImage($profile_image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileImage', [$profile_image]);

        return parent::setProfileImage($profile_image);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitterUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitterUsername', []);

        return parent::getTwitterUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitterUsername($twitter_username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitterUsername', [$twitter_username]);

        return parent::setTwitterUsername($twitter_username);
    }

    /**
     * {@inheritDoc}
     */
    public function getCertificationsCourses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCertificationsCourses', []);

        return parent::getCertificationsCourses();
    }

    /**
     * {@inheritDoc}
     */
    public function setCertificationsCourses($certifications_courses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCertificationsCourses', [$certifications_courses]);

        return parent::setCertificationsCourses($certifications_courses);
    }

    /**
     * {@inheritDoc}
     */
    public function getOtherWorkExperirnce()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOtherWorkExperirnce', []);

        return parent::getOtherWorkExperirnce();
    }

    /**
     * {@inheritDoc}
     */
    public function setOtherWorkExperirnce($other_work_experirnce)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOtherWorkExperirnce', [$other_work_experirnce]);

        return parent::setOtherWorkExperirnce($other_work_experirnce);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserWork()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserWork', []);

        return parent::getUserWork();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserWork($user_work)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserWork', [$user_work]);

        return parent::setUserWork($user_work);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserQualification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserQualification', []);

        return parent::getUserQualification();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserQualification($user_qualification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserQualification', [$user_qualification]);

        return parent::setUserQualification($user_qualification);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserAccount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserAccount', []);

        return parent::getUserAccount();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserAccount($user_account)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserAccount', [$user_account]);

        return parent::setUserAccount($user_account);
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', []);

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', [$firstname]);

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$role]);

        return parent::setRoles($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeeId', []);

        return parent::getEmployeeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployeeId($employee_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployeeId', [$employee_id]);

        return parent::setEmployeeId($employee_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getJWTIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJWTIdentifier', []);

        return parent::getJWTIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getJWTCustomClaims()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJWTCustomClaims', []);

        return parent::getJWTCustomClaims();
    }

    /**
     * {@inheritDoc}
     */
    public function hasPermissionTo($name, $requireAll = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasPermissionTo', [$name, $requireAll]);

        return parent::hasPermissionTo($name, $requireAll);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermissions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermissions', []);

        return parent::getPermissions();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthIdentifierName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthIdentifierName', []);

        return parent::getAuthIdentifierName();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthIdentifier', []);

        return parent::getAuthIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthPassword', []);

        return parent::getAuthPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getRememberToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRememberToken', []);

        return parent::getRememberToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setRememberToken($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRememberToken', [$value]);

        return parent::setRememberToken($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getRememberTokenName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRememberTokenName', []);

        return parent::getRememberTokenName();
    }

    /**
     * {@inheritDoc}
     */
    public function hasRole($role, $requireAll = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRole', [$role, $requireAll]);

        return parent::hasRole($role, $requireAll);
    }

    /**
     * {@inheritDoc}
     */
    public function hasRoleByName($name, $requireAll = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRoleByName', [$name, $requireAll]);

        return parent::hasRoleByName($name, $requireAll);
    }

}
