<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Location extends \App\Entities\Location implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'name', 'address', 'office_start_time', 'office_end_time', 'leave_start_month', 'employee_self_checking', 'overtime_pay', 'half_day_allowed', 'half_day_hours', 'clock_reminder', 'clock_reminder_time', 'late_mark_after_minute', 'allowed_ip', 'working_days', 'alt_sat', 'employees', 'created_at', 'updated_at', 'deletedAt'];
        }

        return ['__isInitialized__', 'id', 'name', 'address', 'office_start_time', 'office_end_time', 'leave_start_month', 'employee_self_checking', 'overtime_pay', 'half_day_allowed', 'half_day_hours', 'clock_reminder', 'clock_reminder_time', 'late_mark_after_minute', 'allowed_ip', 'working_days', 'alt_sat', 'employees', 'created_at', 'updated_at', 'deletedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Location $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getOffice_start_time()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffice_start_time', []);

        return parent::getOffice_start_time();
    }

    /**
     * {@inheritDoc}
     */
    public function getOffice_end_time()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffice_end_time', []);

        return parent::getOffice_end_time();
    }

    /**
     * {@inheritDoc}
     */
    public function getLeave_start_month()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeave_start_month', []);

        return parent::getLeave_start_month();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployee_self_checking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployee_self_checking', []);

        return parent::getEmployee_self_checking();
    }

    /**
     * {@inheritDoc}
     */
    public function getOvertime_pay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOvertime_pay', []);

        return parent::getOvertime_pay();
    }

    /**
     * {@inheritDoc}
     */
    public function getClock_reminder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClock_reminder', []);

        return parent::getClock_reminder();
    }

    /**
     * {@inheritDoc}
     */
    public function getClock_reminder_time()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClock_reminder_time', []);

        return parent::getClock_reminder_time();
    }

    /**
     * {@inheritDoc}
     */
    public function getLate_mark_after_minute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLate_mark_after_minute', []);

        return parent::getLate_mark_after_minute();
    }

    /**
     * {@inheritDoc}
     */
    public function getAllowed_ip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllowed_ip', []);

        return parent::getAllowed_ip();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function setOffice_start_time($office_start_time)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffice_start_time', [$office_start_time]);

        return parent::setOffice_start_time($office_start_time);
    }

    /**
     * {@inheritDoc}
     */
    public function setOffice_end_time($office_end_time)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffice_end_time', [$office_end_time]);

        return parent::setOffice_end_time($office_end_time);
    }

    /**
     * {@inheritDoc}
     */
    public function setLeave_start_month($leave_start_month)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeave_start_month', [$leave_start_month]);

        return parent::setLeave_start_month($leave_start_month);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployee_self_checking($employee_self_checking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployee_self_checking', [$employee_self_checking]);

        return parent::setEmployee_self_checking($employee_self_checking);
    }

    /**
     * {@inheritDoc}
     */
    public function setOvertime_pay($overtime_pay)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOvertime_pay', [$overtime_pay]);

        return parent::setOvertime_pay($overtime_pay);
    }

    /**
     * {@inheritDoc}
     */
    public function setClock_reminder($clock_reminder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClock_reminder', [$clock_reminder]);

        return parent::setClock_reminder($clock_reminder);
    }

    /**
     * {@inheritDoc}
     */
    public function setClock_reminder_time($clock_reminder_time)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClock_reminder_time', [$clock_reminder_time]);

        return parent::setClock_reminder_time($clock_reminder_time);
    }

    /**
     * {@inheritDoc}
     */
    public function setLate_mark_after_minute($late_mark_after_minute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLate_mark_after_minute', [$late_mark_after_minute]);

        return parent::setLate_mark_after_minute($late_mark_after_minute);
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowed_ip($allowed_ip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowed_ip', [$allowed_ip]);

        return parent::setAllowed_ip($allowed_ip);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkingDays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkingDays', []);

        return parent::getWorkingDays();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkingDays($working_days): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkingDays', [$working_days]);

        parent::setWorkingDays($working_days);
    }

    /**
     * {@inheritDoc}
     */
    public function getAltSat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAltSat', []);

        return parent::getAltSat();
    }

    /**
     * {@inheritDoc}
     */
    public function setAltSat($alt_sat): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAltSat', [$alt_sat]);

        parent::setAltSat($alt_sat);
    }

    /**
     * {@inheritDoc}
     */
    public function getHalfDayAllowed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHalfDayAllowed', []);

        return parent::getHalfDayAllowed();
    }

    /**
     * {@inheritDoc}
     */
    public function setHalfDayAllowed($half_day_allowed): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHalfDayAllowed', [$half_day_allowed]);

        parent::setHalfDayAllowed($half_day_allowed);
    }

    /**
     * {@inheritDoc}
     */
    public function getHalfDayHours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHalfDayHours', []);

        return parent::getHalfDayHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setHalfDayHours($half_day_hours): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHalfDayHours', [$half_day_hours]);

        parent::setHalfDayHours($half_day_hours);
    }

}
