<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User_account extends \App\Entities\User_account implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'account_type', 'account_holder_name', 'account_name', 'bank_code', 'crn_number', 'account_number', 'bank_branch', 'bank_name', 'user', 'created_at', 'updated_at', 'deletedAt'];
        }

        return ['__isInitialized__', 'id', 'account_type', 'account_holder_name', 'account_name', 'bank_code', 'crn_number', 'account_number', 'bank_branch', 'bank_name', 'user', 'created_at', 'updated_at', 'deletedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User_account $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountNumber', []);

        return parent::getAccountNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccountNumber($account_number): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccountNumber', [$account_number]);

        parent::setAccountNumber($account_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getCrnNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCrnNumber', []);

        return parent::getCrnNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setCrnNumber($crn_number): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCrnNumber', [$crn_number]);

        parent::setCrnNumber($crn_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccount_type()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccount_type', []);

        return parent::getAccount_type();
    }

    /**
     * {@inheritDoc}
     */
    public function getAccount_holder_name()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccount_holder_name', []);

        return parent::getAccount_holder_name();
    }

    /**
     * {@inheritDoc}
     */
    public function getAccount_name()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccount_name', []);

        return parent::getAccount_name();
    }

    /**
     * {@inheritDoc}
     */
    public function getBank_code()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBank_code', []);

        return parent::getBank_code();
    }

    /**
     * {@inheritDoc}
     */
    public function getBank_branch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBank_branch', []);

        return parent::getBank_branch();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccount_type($account_type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccount_type', [$account_type]);

        return parent::setAccount_type($account_type);
    }

    /**
     * {@inheritDoc}
     */
    public function setAccount_holder_name($account_holder_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccount_holder_name', [$account_holder_name]);

        return parent::setAccount_holder_name($account_holder_name);
    }

    /**
     * {@inheritDoc}
     */
    public function setAccount_name($account_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccount_name', [$account_name]);

        return parent::setAccount_name($account_name);
    }

    /**
     * {@inheritDoc}
     */
    public function setBank_code($bank_code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBank_code', [$bank_code]);

        return parent::setBank_code($bank_code);
    }

    /**
     * {@inheritDoc}
     */
    public function setBank_branch($bank_branch)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBank_branch', [$bank_branch]);

        return parent::setBank_branch($bank_branch);
    }

    /**
     * {@inheritDoc}
     */
    public function getBank_name()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBank_name', []);

        return parent::getBank_name();
    }

    /**
     * {@inheritDoc}
     */
    public function setBank_name($bank_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBank_name', [$bank_name]);

        return parent::setBank_name($bank_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

}
