<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProjectBa extends \App\Entities\ProjectBa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'project_id', 'est_time', 'flag', 'jr_ba_flag', 'emp_id', 'project_jr_ba', 'assigned_jr_ba', 'created_at', 'updated_at', 'deletedAt'];
        }

        return ['__isInitialized__', 'id', 'project_id', 'est_time', 'flag', 'jr_ba_flag', 'emp_id', 'project_jr_ba', 'assigned_jr_ba', 'created_at', 'updated_at', 'deletedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProjectBa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectId', []);

        return parent::getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectId($project_id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectId', [$project_id]);

        parent::setProjectId($project_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstTime', []);

        return parent::getEstTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstTime($est_time): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstTime', [$est_time]);

        parent::setEstTime($est_time);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlag', []);

        return parent::getFlag();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlag($flag): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlag', [$flag]);

        parent::setFlag($flag);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpId', []);

        return parent::getEmpId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpId($emp_id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpId', [$emp_id]);

        parent::setEmpId($emp_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssignedJrBa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssignedJrBa', []);

        return parent::getAssignedJrBa();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssignedJrBa($assigned_jr_ba): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssignedJrBa', [$assigned_jr_ba]);

        parent::setAssignedJrBa($assigned_jr_ba);
    }

    /**
     * {@inheritDoc}
     */
    public function getJrBaFlag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJrBaFlag', []);

        return parent::getJrBaFlag();
    }

    /**
     * {@inheritDoc}
     */
    public function setJrBaFlag($jr_ba_flag): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJrBaFlag', [$jr_ba_flag]);

        parent::setJrBaFlag($jr_ba_flag);
    }

}
