<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EmailSetting extends \App\Entities\EmailSetting implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'admin_emails', 'hr_emails', 'cto_emails', 'hr_contact_number', 'hr_name', 'company_site', 'company_address', 'created_at', 'updated_at', 'deletedAt'];
        }

        return ['__isInitialized__', 'id', 'admin_emails', 'hr_emails', 'cto_emails', 'hr_contact_number', 'hr_name', 'company_site', 'company_address', 'created_at', 'updated_at', 'deletedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EmailSetting $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAdminEmails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminEmails', []);

        return parent::getAdminEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminEmails($admin_emails): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminEmails', [$admin_emails]);

        parent::setAdminEmails($admin_emails);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrEmails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrEmails', []);

        return parent::getHrEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrEmails($hr_emails): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrEmails', [$hr_emails]);

        parent::setHrEmails($hr_emails);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtoEmails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtoEmails', []);

        return parent::getCtoEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtoEmails($cto_emails): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtoEmails', [$cto_emails]);

        parent::setCtoEmails($cto_emails);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrContactNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrContactNumber', []);

        return parent::getHrContactNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrContactNumber($hr_contact_number): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrContactNumber', [$hr_contact_number]);

        parent::setHrContactNumber($hr_contact_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrName', []);

        return parent::getHrName();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrName($hr_name): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrName', [$hr_name]);

        parent::setHrName($hr_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanySite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanySite', []);

        return parent::getCompanySite();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanySite($company_site): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanySite', [$company_site]);

        parent::setCompanySite($company_site);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyAddress', []);

        return parent::getCompanyAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyAddress($company_address): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyAddress', [$company_address]);

        parent::setCompanyAddress($company_address);
    }

}
